### ISSUE TITLE
Citrix Hypervisor 8.2 CU1 Error

### ISSUE THREAD

**Issue by cszheng1** [MikeDombo/xen-exporter#10]
```
172.17.0.1 - - [08/Sep/2023 09:28:29] "GET /metrics HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('172.17.0.1', 45696)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/app/xen-exporter.py", line 222, in __init__
    super().__init__(request, client_address, server)
  File "/usr/local/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.10/http/server.py", line 421, in handle_one_request

    method()
  File "/app/xen-exporter.py", line 228, in do_GET
    self.wfile.write(collect_metrics().encode("utf-8"))
  File "/app/xen-exporter.py", line 140, in collect_metrics
    res = urllib.request.urlopen(
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Error
----------------------------------------
```

**Comment by MikeDombo** [comment]
Your server is returning http 500 you will need to look at its logs.

This is not tested against citrix.
