### ISSUE TITLE
Has been running great until now

### ISSUE THREAD

**Issue by jadsy2107** [MikeDombo/xen-exporter#7]
Hi Mike, great repo thanks for your work !

All of a sudden we are seeing these errors: 
```
192.168.0.13 - - [24/Jul/2023 03:27:09] "GET /metrics HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('192.168.0.13', 35788)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/app/xen-exporter.py", line 222, in __init__
    super().__init__(request, client_address, server)
  File "/usr/local/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/app/xen-exporter.py", line 228, in do_GET
    self.wfile.write(collect_metrics().encode("utf-8"))
  File "/app/xen-exporter.py", line 140, in collect_metrics
    res = urllib.request.urlopen(
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Error
```

Any idea as to what is causing this , metric data is definitely being effected, see below ?

<img width="717" alt="Screenshot 2023-07-24 at 1 29 38 pm" src="https://github.com/MikeDombo/xen-exporter/assets/107200645/70f9dc8d-2746-42ef-a8a3-9078c1a73cb0">

**Comment by MikeDombo** [comment]
The http 500 should be coming from your xcpng server, rather than anything with this code here. You can review the logs on your xcpng server to try and understand what the reason for the internal error is.

**Comment by MikeDombo** [comment]
https://github.com/MikeDombo/xen-exporter/issues/3#issuecomment-1374196002

**Comment by jadsy2107** [comment]
In the `/var/log/xcp-rrdd-plugins.log` file I see a lot of this, although don't know if it's related. 

```
xcp-rrdd-gpumon: [error||0 ||xcp-rrdd-gpumon] Unexpected error (Failure "not enough memory"), sleeping for 10 seconds...
```

What would I be looking for ?

**Comment by jadsy2107** [comment]
I've checked `/metrics` endpoint running on the docker container, its blank, and the error in docker logs shows: 

```
----------------------------------------
192.168.0.1 - - [24/Jul/2023 06:07:36] "GET /metrics HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('192.168.0.1', 58424)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/app/xen-exporter.py", line 222, in __init__
    super().__init__(request, client_address, server)
  File "/usr/local/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/app/xen-exporter.py", line 228, in do_GET
    self.wfile.write(collect_metrics().encode("utf-8"))
  File "/app/xen-exporter.py", line 140, in collect_metrics
    res = urllib.request.urlopen(
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Error
----------------------------------------
```
